server:
  port: 8888
#注册到eureka注册中心
eureka:
  client:
    enabled: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          #配置github
          uri: https://github.com/yutianhao0330/sc-cloud-thyu-config.git
          #配置搜索目录
          search-paths:
            - projecta/configpath
      #配置分支
      label: master
