spring:
  application:
    name: sc-gateway
  cloud:
    gateway:
      routes:
          #自定义的路由名
        - id: myrute
          #规则
          predicates:
            - Path=/goodsSer/**
          uri: http://localhost:8809
          #去掉前缀
          filters:
            - StripPrefix=1

        - id: mybalance
          #规则
          predicates:
            #根据请求路径匹配
            - Path=/gs/**
          uri: lb://sc-user-service
          #去掉前缀
          filters:
            - StripPrefix=1
            #限流配置
            - name: RequestRateLimiter
              args:
                #用于限流的键的解析器的 Bean 对象的名字,使用 SpEL 表达式根据#{@beanName}从 Spring 容器中获取 Bean 对象
                key-resolver: '#{@hostAddrKeyResolver}'
                #令牌桶每秒填充平均速率
                redis-rate-limiter.replenishRate: 5
                #令牌桶总容量
                redis-rate-limiter.burstCapacity: 100
      #支持通过服务名定位服务
      discovery:
        locator:
          enabled: true
      #跨域配置
      globalcors:
        cors-configurations:
          '[/**]':
            # 允许携带认证信息
            # 允许跨域的源(网站域名/ip)，设置*为全部
            # 允许跨域请求里的head字段，设置*为全部
            # 允许跨域的method， 默认为GET和OPTIONS，设置*为全部
            # 跨域允许的有效期
            allow-credentials: true
            allowed-origins: "*"
            #- "http://localhost:8080"
            #- "http://localhost:13010"
            allowed-headers: "*"
            allowed-methods:
              - OPTIONS
              - GET
              - POST
            max-age: 3600
  #限流需要用到redis
  redis:
    port: 6379
    host: 192.168.89.128
    database: 0
server:
  port: 8300

eureka:
  client:
    enabled: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/